# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: McMMO

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
  
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: put jar
      run: mkdir staging && cp target/*.jar staging
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: 2.1.228-SNAPSHOT # 设置版本号
        body: |
            这是一个自动构建版本
    - name: Upload artifacts to release
      if: success() && github.event.ref == 'refs/heads/main' # 只在主分支上运行此步骤
      uses: actions/upload-artifact@v3
      with:
        path: staging/*.jar
